spring:
  application:
    name: aston-project

  datasource:
    url: jdbc:postgresql://localhost:5432/aston_project_db
    username: postgres
    password: postgres

    # create-drop ? нужен ли теперь

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092  # Для Fedora используем 29092 порт
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userEventDto:dev.gedfalk.astonproject.dto.UserEventDto
        spring.json.add.type.headers: true
    consumer:
      group-id: user-service-group